<script src="/main/assets/js/vendor/jquery-3.5.1.min.js"></script>
<script src="/main/assets/js/vendor/modernizr-3.7.1.min.js"></script>
<script src="/main/assets/js/popper.min.js"></script>
<script src="/main/assets/js/plugins/jquery-ui.min.js"></script>
<script src="/main/assets/js/bootstrap.min.js"></script>
<script src="/main/assets/js/plugins/plugins.js"></script>
<script src="/main/assets/js/plugins/ajax-contact.js"></script>
<!-- <script src="assets/js/plugins/aos.js"></script> -->
<script src="/main/assets/js/main.js"></script>
<!-- <script src="assets/js/vendor/vendor.min.js"></script>
<script src="assets/js/plugins/plugins.min.js"></script>
<script src="assets/js/main.js"></script> -->
